// sample data array
  var data2014 = [
  {
    "Year": 2014,
    "Code": "saarg",
    "Country": "Argentina",
    "Religion is important": 248,
    "Religion is not important": 183,
    "Believe in God": 938,
    "Doesnt believe in God": 67,
    "Believe in Hell": 450,
    "Doesnt believe in Hell": 517,
    "Children with religious faith": 239,
    "Children without religious faith": 791
  },
  {
    "Year": 2014,
    "Code": "ocaus",
    "Country": "Australia",
    "Religion is important": 208,
    "Religion is not important": 552,
    "Believe in God": 944,
    "Doesnt believe in God": 501,
    "Believe in Hell": 490,
    "Doesnt believe in Hell": 952,
    "Children with religious faith": 224,
    "Children without religious faith": "1,253"
  },
  {
    "Year": 2014,
    "Code": "sabra",
    "Country": "Brazil",
    "Religion is important": 765,
    "Religion is not important": 48,
    "Believe in God": "1,462",
    "Doesnt believe in God": 20,
    "Believe in Hell": 964,
    "Doesnt believe in Hell": 470,
    "Children with religious faith": 740,
    "Children without religious faith": 746
  },
  {
    "Year": 2014,
    "Code": "sacol",
    "Country": "Colombia",
    "Religion is important": 890,
    "Religion is not important": 53,
    "Believe in God": "1,489",
    "Doesnt believe in God": 21,
    "Believe in Hell": 923,
    "Doesnt believe in Hell": 552,
    "Children with religious faith": 912,
    "Children without religious faith": 600
  },
  {
    "Year": 2014,
    "Code": "euest",
    "Country": "Estonia",
    "Religion is important": 116,
    "Religion is not important": 547,
    "Believe in God": 660,
    "Doesnt believe in God": 660,
    "Believe in Hell": 282,
    "Doesnt believe in Hell": "1,046",
    "Children with religious faith": 288,
    "Children without religious faith": "1,245"
  },
  {
    "Year": 2014,
    "Code": "eugeo",
    "Country": "Georgia",
    "Religion is important": "1,021",
    "Religion is not important": 10,
    "Believe in God": "1,192",
    "Doesnt believe in God": 8,
    "Believe in Hell": 802,
    "Doesnt believe in Hell": 291,
    "Children with religious faith": 764,
    "Children without religious faith": 438
  },
  {
    "Year": 2014,
    "Code": "eudeu",
    "Country": "Germany",
    "Religion is important": 268,
    "Religion is not important": 525,
    "Believe in God": "1,286",
    "Doesnt believe in God": 690,
    "Believe in Hell": 387,
    "Doesnt believe in Hell": "1,595",
    "Children with religious faith": 247,
    "Children without religious faith": "1,798"
  },
  {
    "Year": 2014,
    "Code": "ashkg",
    "Country": "Hong Kong",
    "Religion is important": 121,
    "Religion is not important": 226,
    "Believe in God": 580,
    "Doesnt believe in God": 413,
    "Believe in Hell": 490,
    "Doesnt believe in Hell": 501,
    "Children with religious faith": 109,
    "Children without religious faith": 891
  },
  {
    "Year": 2014,
    "Code": "asind",
    "Country": "India",
    "Religion is important": "2,737",
    "Religion is not important": 72,
    "Believe in God": "3,933",
    "Doesnt believe in God": 116,
    "Believe in Hell": "2,302",
    "Doesnt believe in Hell": "1,453",
    "Children with religious faith": "3,388",
    "Children without religious faith": 690
  },
  {
    "Year": 2014,
    "Code": "asjor",
    "Country": "Jordan",
    "Religion is important": "1,120",
    "Religion is not important": 1,
    "Believe in God": "1,200",
    "Doesnt believe in God": "-",
    "Believe in Hell": "1,183",
    "Doesnt believe in Hell": 17,
    "Children with religious faith": 957,
    "Children without religious faith": 243
  },
  {
    "Year": 2014,
    "Code": "askor",
    "Country": "South Korea",
    "Religion is important": 308,
    "Religion is not important": 222,
    "Believe in God": 603,
    "Doesnt believe in God": 592,
    "Believe in Hell": 517,
    "Doesnt believe in Hell": 676,
    "Children with religious faith": 299,
    "Children without religious faith": 901
  },
  {
    "Year": 2014,
    "Code": "aslbn",
    "Country": "Lebanon",
    "Religion is important": 635,
    "Religion is not important": 99,
    "Believe in God": "1,185",
    "Doesnt believe in God": 15,
    "Believe in Hell": "1,103",
    "Doesnt believe in Hell": 97,
    "Children with religious faith": 403,
    "Children without religious faith": 797
  },
  {
    "Year": 2014,
    "Code": "amys",
    "Country": "Malaysia",
    "Religion is important": "1,103",
    "Religion is not important": 3,
    "Believe in God": "1,279",
    "Doesnt believe in God": 21,
    "Believe in Hell": "1,258",
    "Doesnt believe in Hell": 42,
    "Children with religious faith": 830,
    "Children without religious faith": 470
  },
  {
    "Year": 2014,
    "Code": "namex",
    "Country": "Mexico",
    "Religion is important": "1,169",
    "Religion is not important": 99,
    "Believe in God": "1,875",
    "Doesnt believe in God": 123,
    "Believe in Hell": "1,244",
    "Doesnt believe in Hell": 743,
    "Children with religious faith": 706,
    "Children without religious faith": "1,294"
  },
  {
    "Year": 2014,
    "Code": "eunld",
    "Country": "Netherlands",
    "Religion is important": 204,
    "Religion is not important": 833,
    "Believe in God": 908,
    "Doesnt believe in God": 983,
    "Believe in Hell": 234,
    "Doesnt believe in Hell": "1,657",
    "Children with religious faith": 265,
    "Children without religious faith": "1,637"
  },
  {
    "Year": 2014,
    "Code": "afnga",
    "Country": "Nigeria",
    "Religion is important": "1,579",
    "Religion is not important": 12,
    "Believe in God": "1,750",
    "Doesnt believe in God": 9,
    "Believe in Hell": "1,636",
    "Doesnt believe in Hell": 123,
    "Children with religious faith": "1,279",
    "Children without religious faith": 480
  },
  {
    "Year": 2014,
    "Code": "aspak",
    "Country": "Pakistan",
    "Religion is important": "1,074",
    "Religion is not important": 7,
    "Believe in God": "1,200",
    "Doesnt believe in God": "-",
    "Believe in Hell": "1,197",
    "Doesnt believe in Hell": 3,
    "Children with religious faith": 873,
    "Children without religious faith": 327
  },
  {
    "Year": 2014,
    "Code": "saper",
    "Country": "Peru",
    "Religion is important": 604,
    "Religion is not important": 34,
    "Believe in God": "1,178",
    "Doesnt believe in God": 24,
    "Believe in Hell": 738,
    "Doesnt believe in Hell": 399,
    "Children with religious faith": 509,
    "Children without religious faith": 701
  },
  {
    "Year": 2014,
    "Code": "asphl",
    "Country": "Philippines",
    "Religion is important": "1,031",
    "Religion is not important": 3,
    "Believe in God": "1,194",
    "Doesnt believe in God": 6,
    "Believe in Hell": 979,
    "Doesnt believe in Hell": 216,
    "Children with religious faith": 717,
    "Children without religious faith": 483
  },
  {
    "Year": 2014,
    "Code": "eupol",
    "Country": "Poland",
    "Religion is important": 441,
    "Religion is not important": 46,
    "Believe in God": 891,
    "Doesnt believe in God": 46,
    "Believe in Hell": 549,
    "Doesnt believe in Hell": 321,
    "Children with religious faith": 382,
    "Children without religious faith": 584
  },
  {
    "Year": 2014,
    "Code": "asqat",
    "Country": "Qatar",
    "Religion is important": "1,048",
    "Religion is not important": "-",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 898,
    "Children without religious faith": 162
  },
  {
    "Year": 2014,
    "Code": "assgp",
    "Country": "Singapore",
    "Religion is important": 851,
    "Religion is not important": 106,
    "Believe in God": "1,632",
    "Doesnt believe in God": 338,
    "Believe in Hell": "1,536",
    "Doesnt believe in Hell": 432,
    "Children with religious faith": 516,
    "Children without religious faith": "1,456"
  },
  {
    "Year": 2014,
    "Code": "afzaf",
    "Country": "South Africa",
    "Religion is important": "1,969",
    "Religion is not important": 169,
    "Believe in God": "3,414",
    "Doesnt believe in God": 63,
    "Believe in Hell": "1,484",
    "Doesnt believe in Hell": "1,734",
    "Children with religious faith": "1,564",
    "Children without religious faith": "1,967"
  },
  {
    "Year": 2014,
    "Code": "afzwe",
    "Country": "Zimbabwe",
    "Religion is important": "1,252",
    "Religion is not important": 11,
    "Believe in God": "1,490",
    "Doesnt believe in God": 9,
    "Believe in Hell": "1,291",
    "Doesnt believe in Hell": 208,
    "Children with religious faith": 894,
    "Children without religious faith": 605
  },
  {
    "Year": 2014,
    "Code": "euesp",
    "Country": "Spain",
    "Religion is important": 127,
    "Religion is not important": 427,
    "Believe in God": 846,
    "Doesnt believe in God": 269,
    "Believe in Hell": 381,
    "Doesnt believe in Hell": 684,
    "Children with religious faith": 126,
    "Children without religious faith": "1,063"
  },
  {
    "Year": 2014,
    "Code": "euswe",
    "Country": "Sweden",
    "Religion is important": 96,
    "Religion is not important": 413,
    "Believe in God": 494,
    "Doesnt believe in God": 607,
    "Believe in Hell": 174,
    "Doesnt believe in Hell": 975,
    "Children with religious faith": 53,
    "Children without religious faith": "1,153"
  },
  {
    "Year": 2014,
    "Code": "astur",
    "Country": "Turkey",
    "Religion is important": "1,094",
    "Religion is not important": 47,
    "Believe in God": "1,569",
    "Doesnt believe in God": 12,
    "Believe in Hell": "1,550",
    "Doesnt believe in Hell": 46,
    "Children with religious faith": 637,
    "Children without religious faith": 968
  },
  {
    "Year": 2014,
    "Code": "euukr",
    "Country": "Ukraine",
    "Religion is important": 394,
    "Religion is not important": 191,
    "Believe in God": "1,317",
    "Doesnt believe in God": 183,
    "Believe in Hell": 823,
    "Doesnt believe in Hell": 677,
    "Children with religious faith": 334,
    "Children without religious faith": "1,166"
  },
  {
    "Year": 2014,
    "Code": "afegy",
    "Country": "Egypt",
    "Religion is important": "1,434",
    "Religion is not important": 2,
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,270",
    "Children without religious faith": 253
  },
  {
    "Year": 2014,
    "Code": "nausa",
    "Country": "United States",
    "Religion is important": 902,
    "Religion is not important": 284,
    "Believe in God": "1,957",
    "Doesnt believe in God": 248,
    "Believe in Hell": "1,567",
    "Doesnt believe in Hell": 620,
    "Children with religious faith": 961,
    "Children without religious faith": "1,271"
  }
]
 var data2009 = [
  {
    "Year": 2009,
    "Code": "saarg",
    "Country": "Argentina",
    "Religion is important": 332,
    "Religion is not important": 106,
    "Believe in God": 581,
    "Doesnt believe in God": 57,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 257,
    "Children without religious faith": 745
  },
  {
    "Year": 2009,
    "Code": "ocaus",
    "Country": "Australia",
    "Religion is important": 273,
    "Religion is not important": 411,
    "Believe in God": 391,
    "Doesnt believe in God": 218,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 298,
    "Children without religious faith": "1,124"
  },
  {
    "Year": 2009,
    "Code": "sabra",
    "Country": "Brazil",
    "Religion is important": 758,
    "Religion is not important": 41,
    "Believe in God": "1,304",
    "Doesnt believe in God": 15,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 836,
    "Children without religious faith": 664
  },
  {
    "Year": 2009,
    "Code": "sacol",
    "Country": "Colombia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "2,591",
    "Doesnt believe in God": 15,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,443",
    "Children without religious faith": "1,582"
  },
  {
    "Year": 2009,
    "Code": "euest",
    "Country": "Estonia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "eugeo",
    "Country": "Georgia",
    "Religion is important": "1,193",
    "Religion is not important": 13,
    "Believe in God": 938,
    "Doesnt believe in God": 4,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,009",
    "Children without religious faith": 491
  },
  {
    "Year": 2009,
    "Code": "eudeu",
    "Country": "Germany",
    "Religion is important": 226,
    "Religion is not important": 746,
    "Believe in God": 196,
    "Doesnt believe in God": 626,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 193,
    "Children without religious faith": "1,871"
  },
  {
    "Year": 2009,
    "Code": "ashkg",
    "Country": "Hong Kong",
    "Religion is important": 64,
    "Religion is not important": 123,
    "Believe in God": 67,
    "Doesnt believe in God": 261,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 15,
    "Children without religious faith": "1,237"
  },
  {
    "Year": 2009,
    "Code": "asind",
    "Country": "India",
    "Religion is important": 994,
    "Religion is not important": 106,
    "Believe in God": "1,119",
    "Doesnt believe in God": 170,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 826,
    "Children without religious faith": "1,175"
  },
  {
    "Year": 2009,
    "Code": "asjor",
    "Country": "Jordan",
    "Religion is important": "1,133",
    "Religion is not important": 2,
    "Believe in God": "1,156",
    "Doesnt believe in God": 4,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,008",
    "Children without religious faith": 192
  },
  {
    "Year": 2009,
    "Code": "askor",
    "Country": "South Korea",
    "Religion is important": 254,
    "Religion is not important": 223,
    "Believe in God": 156,
    "Doesnt believe in God": 136,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 258,
    "Children without religious faith": 942
  },
  {
    "Year": 2009,
    "Code": "aslbn",
    "Country": "Lebanon",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "amys",
    "Country": "Malaysia",
    "Religion is important": 966,
    "Religion is not important": 8,
    "Believe in God": 484,
    "Doesnt believe in God": 10,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 716,
    "Children without religious faith": 485
  },
  {
    "Year": 2009,
    "Code": "namex",
    "Country": "Mexico",
    "Religion is important": 915,
    "Religion is not important": 53,
    "Believe in God": "1,240",
    "Doesnt believe in God": 14,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 606,
    "Children without religious faith": 954
  },
  {
    "Year": 2009,
    "Code": "eunld",
    "Country": "Netherlands",
    "Religion is important": 126,
    "Religion is not important": 406,
    "Believe in God": 105,
    "Doesnt believe in God": 317,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 102,
    "Children without religious faith": 948
  },
  {
    "Year": 2009,
    "Code": "afnga",
    "Country": "Nigeria",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "aspak",
    "Country": "Pakistan",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "saper",
    "Country": "Peru",
    "Religion is important": 737,
    "Religion is not important": 71,
    "Believe in God": 961,
    "Doesnt believe in God": 18,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 676,
    "Children without religious faith": 824
  },
  {
    "Year": 2009,
    "Code": "asphl",
    "Country": "Philippines",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "eupol",
    "Country": "Poland",
    "Religion is important": 472,
    "Religion is not important": 27,
    "Believe in God": 549,
    "Doesnt believe in God": 13,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 467,
    "Children without religious faith": 533
  },
  {
    "Year": 2009,
    "Code": "asqat",
    "Country": "Qatar",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "assgp",
    "Country": "Singapore",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "afzaf",
    "Country": "South Africa",
    "Religion is important": "2,090",
    "Religion is not important": 89,
    "Believe in God": "1,956",
    "Doesnt believe in God": 13,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,678",
    "Children without religious faith": "1,310"
  },
  {
    "Year": 2009,
    "Code": "afzwe",
    "Country": "Zimbabwe",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "euesp",
    "Country": "Spain",
    "Religion is important": 178,
    "Religion is not important": 356,
    "Believe in God": 159,
    "Doesnt believe in God": 214,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 135,
    "Children without religious faith": "1,065"
  },
  {
    "Year": 2009,
    "Code": "euswe",
    "Country": "Sweden",
    "Religion is important": 93,
    "Religion is not important": 297,
    "Believe in God": 75,
    "Doesnt believe in God": 331,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 61,
    "Children without religious faith": 942
  },
  {
    "Year": 2009,
    "Code": "astur",
    "Country": "Turkey",
    "Religion is important": "1,004",
    "Religion is not important": 34,
    "Believe in God": "1,021",
    "Doesnt believe in God": 11,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 567,
    "Children without religious faith": 779
  },
  {
    "Year": 2009,
    "Code": "euukr",
    "Country": "Ukraine",
    "Religion is important": 176,
    "Religion is not important": 146,
    "Believe in God": 272,
    "Doesnt believe in God": 49,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 156,
    "Children without religious faith": 844
  },
  {
    "Year": 2009,
    "Code": "afegy",
    "Country": "Egypt",
    "Religion is important": "2,911",
    "Religion is not important": 7,
    "Believe in God": "2,956",
    "Doesnt believe in God": 12,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "2,739",
    "Children without religious faith": 312
  },
  {
    "Year": 2009,
    "Code": "nausa",
    "Country": "United States",
    "Religion is important": 587,
    "Religion is not important": 108,
    "Believe in God": 691,
    "Doesnt believe in God": 64,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 632,
    "Children without religious faith": 617
  }
 ]