// sample data array
  var data2014 = [
  {
    "Year": 2014,
    "Code": "saarg",
    "Country": "Argentina",
    "Religion is important": 248,
    "Religion is not important": 183,
    "Believe in God": 938,
    "Doesnt believe in God": 67,
    "Believe in Hell": 450,
    "Doesnt believe in Hell": 517,
    "Children with religious faith": 239,
    "Children without religious faith": 791
  },
  {
    "Year": 2014,
    "Code": "ocaus",
    "Country": "Australia",
    "Religion is important": 208,
    "Religion is not important": 552,
    "Believe in God": 944,
    "Doesnt believe in God": 501,
    "Believe in Hell": 490,
    "Doesnt believe in Hell": 952,
    "Children with religious faith": 224,
    "Children without religious faith": "1,253"
  },
  {
    "Year": 2014,
    "Code": "sabra",
    "Country": "Brazil",
    "Religion is important": 765,
    "Religion is not important": 48,
    "Believe in God": "1,462",
    "Doesnt believe in God": 20,
    "Believe in Hell": 964,
    "Doesnt believe in Hell": 470,
    "Children with religious faith": 740,
    "Children without religious faith": 746
  },
  {
    "Year": 2014,
    "Code": "sacol",
    "Country": "Colombia",
    "Religion is important": 890,
    "Religion is not important": 53,
    "Believe in God": "1,489",
    "Doesnt believe in God": 21,
    "Believe in Hell": 923,
    "Doesnt believe in Hell": 552,
    "Children with religious faith": 912,
    "Children without religious faith": 600
  },
  {
    "Year": 2014,
    "Code": "euest",
    "Country": "Estonia",
    "Religion is important": 116,
    "Religion is not important": 547,
    "Believe in God": 660,
    "Doesnt believe in God": 660,
    "Believe in Hell": 282,
    "Doesnt believe in Hell": "1,046",
    "Children with religious faith": 288,
    "Children without religious faith": "1,245"
  },
  {
    "Year": 2014,
    "Code": "eugeo",
    "Country": "Georgia",
    "Religion is important": "1,021",
    "Religion is not important": 10,
    "Believe in God": "1,192",
    "Doesnt believe in God": 8,
    "Believe in Hell": 802,
    "Doesnt believe in Hell": 291,
    "Children with religious faith": 764,
    "Children without religious faith": 438
  },
  {
    "Year": 2014,
    "Code": "eudeu",
    "Country": "Germany",
    "Religion is important": 268,
    "Religion is not important": 525,
    "Believe in God": "1,286",
    "Doesnt believe in God": 690,
    "Believe in Hell": 387,
    "Doesnt believe in Hell": "1,595",
    "Children with religious faith": 247,
    "Children without religious faith": "1,798"
  },
  {
    "Year": 2014,
    "Code": "ashkg",
    "Country": "Hong Kong",
    "Religion is important": 121,
    "Religion is not important": 226,
    "Believe in God": 580,
    "Doesnt believe in God": 413,
    "Believe in Hell": 490,
    "Doesnt believe in Hell": 501,
    "Children with religious faith": 109,
    "Children without religious faith": 891
  },
  {
    "Year": 2014,
    "Code": "asind",
    "Country": "India",
    "Religion is important": "2,737",
    "Religion is not important": 72,
    "Believe in God": "3,933",
    "Doesnt believe in God": 116,
    "Believe in Hell": "2,302",
    "Doesnt believe in Hell": "1,453",
    "Children with religious faith": "3,388",
    "Children without religious faith": 690
  },
  {
    "Year": 2014,
    "Code": "asjor",
    "Country": "Jordan",
    "Religion is important": "1,120",
    "Religion is not important": 1,
    "Believe in God": "1,200",
    "Doesnt believe in God": "-",
    "Believe in Hell": "1,183",
    "Doesnt believe in Hell": 17,
    "Children with religious faith": 957,
    "Children without religious faith": 243
  },
  {
    "Year": 2014,
    "Code": "askor",
    "Country": "South Korea",
    "Religion is important": 308,
    "Religion is not important": 222,
    "Believe in God": 603,
    "Doesnt believe in God": 592,
    "Believe in Hell": 517,
    "Doesnt believe in Hell": 676,
    "Children with religious faith": 299,
    "Children without religious faith": 901
  },
  {
    "Year": 2014,
    "Code": "aslbn",
    "Country": "Lebanon",
    "Religion is important": 635,
    "Religion is not important": 99,
    "Believe in God": "1,185",
    "Doesnt believe in God": 15,
    "Believe in Hell": "1,103",
    "Doesnt believe in Hell": 97,
    "Children with religious faith": 403,
    "Children without religious faith": 797
  },
  {
    "Year": 2014,
    "Code": "amys",
    "Country": "Malaysia",
    "Religion is important": "1,103",
    "Religion is not important": 3,
    "Believe in God": "1,279",
    "Doesnt believe in God": 21,
    "Believe in Hell": "1,258",
    "Doesnt believe in Hell": 42,
    "Children with religious faith": 830,
    "Children without religious faith": 470
  },
  {
    "Year": 2014,
    "Code": "namex",
    "Country": "Mexico",
    "Religion is important": "1,169",
    "Religion is not important": 99,
    "Believe in God": "1,875",
    "Doesnt believe in God": 123,
    "Believe in Hell": "1,244",
    "Doesnt believe in Hell": 743,
    "Children with religious faith": 706,
    "Children without religious faith": "1,294"
  },
  {
    "Year": 2014,
    "Code": "eunld",
    "Country": "Netherlands",
    "Religion is important": 204,
    "Religion is not important": 833,
    "Believe in God": 908,
    "Doesnt believe in God": 983,
    "Believe in Hell": 234,
    "Doesnt believe in Hell": "1,657",
    "Children with religious faith": 265,
    "Children without religious faith": "1,637"
  },
  {
    "Year": 2014,
    "Code": "afnga",
    "Country": "Nigeria",
    "Religion is important": "1,579",
    "Religion is not important": 12,
    "Believe in God": "1,750",
    "Doesnt believe in God": 9,
    "Believe in Hell": "1,636",
    "Doesnt believe in Hell": 123,
    "Children with religious faith": "1,279",
    "Children without religious faith": 480
  },
  {
    "Year": 2014,
    "Code": "aspak",
    "Country": "Pakistan",
    "Religion is important": "1,074",
    "Religion is not important": 7,
    "Believe in God": "1,200",
    "Doesnt believe in God": "-",
    "Believe in Hell": "1,197",
    "Doesnt believe in Hell": 3,
    "Children with religious faith": 873,
    "Children without religious faith": 327
  },
  {
    "Year": 2014,
    "Code": "saper",
    "Country": "Peru",
    "Religion is important": 604,
    "Religion is not important": 34,
    "Believe in God": "1,178",
    "Doesnt believe in God": 24,
    "Believe in Hell": 738,
    "Doesnt believe in Hell": 399,
    "Children with religious faith": 509,
    "Children without religious faith": 701
  },
  {
    "Year": 2014,
    "Code": "asphl",
    "Country": "Philippines",
    "Religion is important": "1,031",
    "Religion is not important": 3,
    "Believe in God": "1,194",
    "Doesnt believe in God": 6,
    "Believe in Hell": 979,
    "Doesnt believe in Hell": 216,
    "Children with religious faith": 717,
    "Children without religious faith": 483
  },
  {
    "Year": 2014,
    "Code": "eupol",
    "Country": "Poland",
    "Religion is important": 441,
    "Religion is not important": 46,
    "Believe in God": 891,
    "Doesnt believe in God": 46,
    "Believe in Hell": 549,
    "Doesnt believe in Hell": 321,
    "Children with religious faith": 382,
    "Children without religious faith": 584
  },
  {
    "Year": 2014,
    "Code": "asqat",
    "Country": "Qatar",
    "Religion is important": "1,048",
    "Religion is not important": "-",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 898,
    "Children without religious faith": 162
  },
  {
    "Year": 2014,
    "Code": "assgp",
    "Country": "Singapore",
    "Religion is important": 851,
    "Religion is not important": 106,
    "Believe in God": "1,632",
    "Doesnt believe in God": 338,
    "Believe in Hell": "1,536",
    "Doesnt believe in Hell": 432,
    "Children with religious faith": 516,
    "Children without religious faith": "1,456"
  },
  {
    "Year": 2014,
    "Code": "afzaf",
    "Country": "South Africa",
    "Religion is important": "1,969",
    "Religion is not important": 169,
    "Believe in God": "3,414",
    "Doesnt believe in God": 63,
    "Believe in Hell": "1,484",
    "Doesnt believe in Hell": "1,734",
    "Children with religious faith": "1,564",
    "Children without religious faith": "1,967"
  },
  {
    "Year": 2014,
    "Code": "afzwe",
    "Country": "Zimbabwe",
    "Religion is important": "1,252",
    "Religion is not important": 11,
    "Believe in God": "1,490",
    "Doesnt believe in God": 9,
    "Believe in Hell": "1,291",
    "Doesnt believe in Hell": 208,
    "Children with religious faith": 894,
    "Children without religious faith": 605
  },
  {
    "Year": 2014,
    "Code": "euesp",
    "Country": "Spain",
    "Religion is important": 127,
    "Religion is not important": 427,
    "Believe in God": 846,
    "Doesnt believe in God": 269,
    "Believe in Hell": 381,
    "Doesnt believe in Hell": 684,
    "Children with religious faith": 126,
    "Children without religious faith": "1,063"
  },
  {
    "Year": 2014,
    "Code": "euswe",
    "Country": "Sweden",
    "Religion is important": 96,
    "Religion is not important": 413,
    "Believe in God": 494,
    "Doesnt believe in God": 607,
    "Believe in Hell": 174,
    "Doesnt believe in Hell": 975,
    "Children with religious faith": 53,
    "Children without religious faith": "1,153"
  },
  {
    "Year": 2014,
    "Code": "astur",
    "Country": "Turkey",
    "Religion is important": "1,094",
    "Religion is not important": 47,
    "Believe in God": "1,569",
    "Doesnt believe in God": 12,
    "Believe in Hell": "1,550",
    "Doesnt believe in Hell": 46,
    "Children with religious faith": 637,
    "Children without religious faith": 968
  },
  {
    "Year": 2014,
    "Code": "euukr",
    "Country": "Ukraine",
    "Religion is important": 394,
    "Religion is not important": 191,
    "Believe in God": "1,317",
    "Doesnt believe in God": 183,
    "Believe in Hell": 823,
    "Doesnt believe in Hell": 677,
    "Children with religious faith": 334,
    "Children without religious faith": "1,166"
  },
  {
    "Year": 2014,
    "Code": "afegy",
    "Country": "Egypt",
    "Religion is important": "1,434",
    "Religion is not important": 2,
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,270",
    "Children without religious faith": 253
  },
  {
    "Year": 2014,
    "Code": "nausa",
    "Country": "United States",
    "Religion is important": 902,
    "Religion is not important": 284,
    "Believe in God": "1,957",
    "Doesnt believe in God": 248,
    "Believe in Hell": "1,567",
    "Doesnt believe in Hell": 620,
    "Children with religious faith": 961,
    "Children without religious faith": "1,271"
  }
]
 var data2009 = [
  {
    "Year": 2009,
    "Code": "saarg",
    "Country": "Argentina",
    "Religion is important": 332,
    "Religion is not important": 106,
    "Believe in God": 581,
    "Doesnt believe in God": 57,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 257,
    "Children without religious faith": 745
  },
  {
    "Year": 2009,
    "Code": "ocaus",
    "Country": "Australia",
    "Religion is important": 273,
    "Religion is not important": 411,
    "Believe in God": 391,
    "Doesnt believe in God": 218,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 298,
    "Children without religious faith": "1,124"
  },
  {
    "Year": 2009,
    "Code": "sabra",
    "Country": "Brazil",
    "Religion is important": 758,
    "Religion is not important": 41,
    "Believe in God": "1,304",
    "Doesnt believe in God": 15,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 836,
    "Children without religious faith": 664
  },
  {
    "Year": 2009,
    "Code": "sacol",
    "Country": "Colombia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "2,591",
    "Doesnt believe in God": 15,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,443",
    "Children without religious faith": "1,582"
  },
  {
    "Year": 2009,
    "Code": "euest",
    "Country": "Estonia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "eugeo",
    "Country": "Georgia",
    "Religion is important": "1,193",
    "Religion is not important": 13,
    "Believe in God": 938,
    "Doesnt believe in God": 4,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,009",
    "Children without religious faith": 491
  },
  {
    "Year": 2009,
    "Code": "eudeu",
    "Country": "Germany",
    "Religion is important": 226,
    "Religion is not important": 746,
    "Believe in God": 196,
    "Doesnt believe in God": 626,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 193,
    "Children without religious faith": "1,871"
  },
  {
    "Year": 2009,
    "Code": "ashkg",
    "Country": "Hong Kong",
    "Religion is important": 64,
    "Religion is not important": 123,
    "Believe in God": 67,
    "Doesnt believe in God": 261,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 15,
    "Children without religious faith": "1,237"
  },
  {
    "Year": 2009,
    "Code": "asind",
    "Country": "India",
    "Religion is important": 994,
    "Religion is not important": 106,
    "Believe in God": "1,119",
    "Doesnt believe in God": 170,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 826,
    "Children without religious faith": "1,175"
  },
  {
    "Year": 2009,
    "Code": "asjor",
    "Country": "Jordan",
    "Religion is important": "1,133",
    "Religion is not important": 2,
    "Believe in God": "1,156",
    "Doesnt believe in God": 4,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,008",
    "Children without religious faith": 192
  },
  {
    "Year": 2009,
    "Code": "askor",
    "Country": "South Korea",
    "Religion is important": 254,
    "Religion is not important": 223,
    "Believe in God": 156,
    "Doesnt believe in God": 136,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 258,
    "Children without religious faith": 942
  },
  {
    "Year": 2009,
    "Code": "aslbn",
    "Country": "Lebanon",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "amys",
    "Country": "Malaysia",
    "Religion is important": 966,
    "Religion is not important": 8,
    "Believe in God": 484,
    "Doesnt believe in God": 10,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 716,
    "Children without religious faith": 485
  },
  {
    "Year": 2009,
    "Code": "namex",
    "Country": "Mexico",
    "Religion is important": 915,
    "Religion is not important": 53,
    "Believe in God": "1,240",
    "Doesnt believe in God": 14,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 606,
    "Children without religious faith": 954
  },
  {
    "Year": 2009,
    "Code": "eunld",
    "Country": "Netherlands",
    "Religion is important": 126,
    "Religion is not important": 406,
    "Believe in God": 105,
    "Doesnt believe in God": 317,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 102,
    "Children without religious faith": 948
  },
  {
    "Year": 2009,
    "Code": "afnga",
    "Country": "Nigeria",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "aspak",
    "Country": "Pakistan",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "saper",
    "Country": "Peru",
    "Religion is important": 737,
    "Religion is not important": 71,
    "Believe in God": 961,
    "Doesnt believe in God": 18,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 676,
    "Children without religious faith": 824
  },
  {
    "Year": 2009,
    "Code": "asphl",
    "Country": "Philippines",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "eupol",
    "Country": "Poland",
    "Religion is important": 472,
    "Religion is not important": 27,
    "Believe in God": 549,
    "Doesnt believe in God": 13,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 467,
    "Children without religious faith": 533
  },
  {
    "Year": 2009,
    "Code": "asqat",
    "Country": "Qatar",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "assgp",
    "Country": "Singapore",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "afzaf",
    "Country": "South Africa",
    "Religion is important": "2,090",
    "Religion is not important": 89,
    "Believe in God": "1,956",
    "Doesnt believe in God": 13,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,678",
    "Children without religious faith": "1,310"
  },
  {
    "Year": 2009,
    "Code": "afzwe",
    "Country": "Zimbabwe",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2009,
    "Code": "euesp",
    "Country": "Spain",
    "Religion is important": 178,
    "Religion is not important": 356,
    "Believe in God": 159,
    "Doesnt believe in God": 214,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 135,
    "Children without religious faith": "1,065"
  },
  {
    "Year": 2009,
    "Code": "euswe",
    "Country": "Sweden",
    "Religion is important": 93,
    "Religion is not important": 297,
    "Believe in God": 75,
    "Doesnt believe in God": 331,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 61,
    "Children without religious faith": 942
  },
  {
    "Year": 2009,
    "Code": "astur",
    "Country": "Turkey",
    "Religion is important": "1,004",
    "Religion is not important": 34,
    "Believe in God": "1,021",
    "Doesnt believe in God": 11,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 567,
    "Children without religious faith": 779
  },
  {
    "Year": 2009,
    "Code": "euukr",
    "Country": "Ukraine",
    "Religion is important": 176,
    "Religion is not important": 146,
    "Believe in God": 272,
    "Doesnt believe in God": 49,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 156,
    "Children without religious faith": 844
  },
  {
    "Year": 2009,
    "Code": "afegy",
    "Country": "Egypt",
    "Religion is important": "2,911",
    "Religion is not important": 7,
    "Believe in God": "2,956",
    "Doesnt believe in God": 12,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "2,739",
    "Children without religious faith": 312
  },
  {
    "Year": 2009,
    "Code": "nausa",
    "Country": "United States",
    "Religion is important": 587,
    "Religion is not important": 108,
    "Believe in God": 691,
    "Doesnt believe in God": 64,
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 632,
    "Children without religious faith": 617
  }
 ]
 var data2004 = [
  {
    "Year": 2004,
    "Code": "saarg",
    "Country": "Argentina",
    "Religion is important": 592,
    "Religion is not important": 111,
    "Believe in God": "1,220",
    "Doesnt believe in God": 46,
    "Believe in Hell": 516,
    "Doesnt believe in Hell": 665,
    "Children with religious faith": 557,
    "Children without religious faith": 723
  },
  {
    "Year": 2004,
    "Code": "ocaus",
    "Country": "Australia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "sabra",
    "Country": "Brazil",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "sacol",
    "Country": "Colombia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "euest",
    "Country": "Estonia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "eugeo",
    "Country": "Georgia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "eudeu",
    "Country": "Germany",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "ashkg",
    "Country": "Hong Kong",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "asind",
    "Country": "India",
    "Religion is important": "1,117",
    "Religion is not important": 143,
    "Believe in God": "1,871",
    "Doesnt believe in God": 104,
    "Believe in Hell": "1,239",
    "Doesnt believe in Hell": 570,
    "Children with religious faith": 933,
    "Children without religious faith": "1,069"
  },
  {
    "Year": 2004,
    "Code": "asjor",
    "Country": "Jordan",
    "Religion is important": "1,173",
    "Religion is not important": 4,
    "Believe in God": "1,219",
    "Doesnt believe in God": 3,
    "Believe in Hell": "1,210",
    "Doesnt believe in Hell": 8,
    "Children with religious faith": "1,027",
    "Children without religious faith": 197
  },
  {
    "Year": 2004,
    "Code": "askor",
    "Country": "South Korea",
    "Religion is important": 279,
    "Religion is not important": 197,
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 254,
    "Children without religious faith": 946
  },
  {
    "Year": 2004,
    "Code": "aslbn",
    "Country": "Lebanon",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "amys",
    "Country": "Malaysia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "namex",
    "Country": "Mexico",
    "Religion is important": "1,039",
    "Religion is not important": 48,
    "Believe in God": "1,500",
    "Doesnt believe in God": 30,
    "Believe in Hell": "1,083",
    "Doesnt believe in Hell": 369,
    "Children with religious faith": 815,
    "Children without religious faith": 720
  },
  {
    "Year": 2004,
    "Code": "eunld",
    "Country": "Netherlands",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "afnga",
    "Country": "Nigeria",
    "Religion is important": "1,876",
    "Religion is not important": 5,
    "Believe in God": "2,013",
    "Doesnt believe in God": 7,
    "Believe in Hell": "1,871",
    "Doesnt believe in Hell": 127,
    "Children with religious faith": "1,369",
    "Children without religious faith": 653
  },
  {
    "Year": 2004,
    "Code": "aspak",
    "Country": "Pakistan",
    "Religion is important": "1,635",
    "Religion is not important": 10,
    "Believe in God": "2,000",
    "Doesnt believe in God": "-",
    "Believe in Hell": "2,000",
    "Doesnt believe in Hell": "-",
    "Children with religious faith": "1,725",
    "Children without religious faith": 275
  },
  {
    "Year": 2004,
    "Code": "saper",
    "Country": "Peru",
    "Religion is important": 788,
    "Religion is not important": 31,
    "Believe in God": "1,471",
    "Doesnt believe in God": 23,
    "Believe in Hell": 920,
    "Doesnt believe in Hell": 491,
    "Children with religious faith": 834,
    "Children without religious faith": 667
  },
  {
    "Year": 2004,
    "Code": "asphl",
    "Country": "Philippines",
    "Religion is important": "1,042",
    "Religion is not important": 4,
    "Believe in God": "1,191",
    "Doesnt believe in God": 7,
    "Believe in Hell": "1,046",
    "Doesnt believe in Hell": 85,
    "Children with religious faith": 712,
    "Children without religious faith": 488
  },
  {
    "Year": 2004,
    "Code": "eupol",
    "Country": "Poland",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "asqat",
    "Country": "Qatar",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "assgp",
    "Country": "Singapore",
    "Religion is important": 543,
    "Religion is not important": 102,
    "Believe in God": "1,267",
    "Doesnt believe in God": 188,
    "Believe in Hell": "1,113",
    "Doesnt believe in Hell": 293,
    "Children with religious faith": 455,
    "Children without religious faith": "1,058"
  },
  {
    "Year": 2004,
    "Code": "afzaf",
    "Country": "South Africa",
    "Religion is important": "2,091",
    "Religion is not important": 94,
    "Believe in God": "2,950",
    "Doesnt believe in God": 35,
    "Believe in Hell": "1,661",
    "Doesnt believe in Hell": "1,085",
    "Children with religious faith": "1,843",
    "Children without religious faith": "1,158"
  },
  {
    "Year": 2004,
    "Code": "afzwe",
    "Country": "Zimbabwe",
    "Religion is important": 778,
    "Religion is not important": 24,
    "Believe in God": 992,
    "Doesnt believe in God": 6,
    "Believe in Hell": 728,
    "Doesnt believe in Hell": 188,
    "Children with religious faith": 743,
    "Children without religious faith": 259
  },
  {
    "Year": 2004,
    "Code": "euesp",
    "Country": "Spain",
    "Religion is important": 265,
    "Religion is not important": 233,
    "Believe in God": 948,
    "Doesnt believe in God": 195,
    "Believe in Hell": 403,
    "Doesnt believe in Hell": 602,
    "Children with religious faith": 245,
    "Children without religious faith": 964
  },
  {
    "Year": 2004,
    "Code": "euswe",
    "Country": "Sweden",
    "Religion is important": 108,
    "Religion is not important": 226,
    "Believe in God": 472,
    "Doesnt believe in God": 412,
    "Believe in Hell": 89,
    "Doesnt believe in Hell": 856,
    "Children with religious faith": 49,
    "Children without religious faith": 965
  },
  {
    "Year": 2004,
    "Code": "astur",
    "Country": "Turkey",
    "Religion is important": "2,731",
    "Religion is not important": 91,
    "Believe in God": "3,314",
    "Doesnt believe in God": 65,
    "Believe in Hell": "3,155",
    "Doesnt believe in Hell": 206,
    "Children with religious faith": "1,501",
    "Children without religious faith": "1,901"
  },
  {
    "Year": 2004,
    "Code": "euukr",
    "Country": "Ukraine",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 2004,
    "Code": "afegy",
    "Country": "Egypt",
    "Religion is important": "2,920",
    "Religion is not important": "-",
    "Believe in God": "3,000",
    "Doesnt believe in God": "-",
    "Believe in Hell": "3,000",
    "Doesnt believe in Hell": "-",
    "Children with religious faith": "2,620",
    "Children without religious faith": 380
  },
  {
    "Year": 2004,
    "Code": "nausa",
    "Country": "United States",
    "Religion is important": 683,
    "Religion is not important": 59,
    "Believe in God": "1,130",
    "Doesnt believe in God": 51,
    "Believe in Hell": 853,
    "Doesnt believe in Hell": 291,
    "Children with religious faith": 625,
    "Children without religious faith": 575
  }
]
var data2009 = [
  {
    "Year": 1999,
    "Code": "saarg",
    "Country": "Argentina",
    "Religion is important": 376,
    "Religion is not important": 127,
    "Believe in God": "1,009",
    "Doesnt believe in God": 55,
    "Believe in Hell": 469,
    "Doesnt believe in Hell": 548,
    "Children with religious faith": 374,
    "Children without religious faith": 705
  },
  {
    "Year": 1999,
    "Code": "ocaus",
    "Country": "Australia",
    "Religion is important": 474,
    "Religion is not important": 393,
    "Believe in God": "1,543",
    "Doesnt believe in God": 383,
    "Believe in Hell": 784,
    "Doesnt believe in Hell": "1,124",
    "Children with religious faith": 438,
    "Children without religious faith": "1,610"
  },
  {
    "Year": 1999,
    "Code": "sabra",
    "Country": "Brazil",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "sacol",
    "Country": "Colombia",
    "Religion is important": "1,323",
    "Religion is not important": "-",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "1,483",
    "Children without religious faith": "1,546"
  },
  {
    "Year": 1999,
    "Code": "euest",
    "Country": "Estonia",
    "Religion is important": 81,
    "Religion is not important": 334,
    "Believe in God": 468,
    "Doesnt believe in God": 436,
    "Believe in Hell": 150,
    "Doesnt believe in Hell": 723,
    "Children with religious faith": 51,
    "Children without religious faith": 970
  },
  {
    "Year": 1999,
    "Code": "eugeo",
    "Country": "Georgia",
    "Religion is important": 989,
    "Religion is not important": 113,
    "Believe in God": "1,826",
    "Doesnt believe in God": 134,
    "Believe in Hell": "1,043",
    "Doesnt believe in Hell": 716,
    "Children with religious faith": 623,
    "Children without religious faith": "1,385"
  },
  {
    "Year": 1999,
    "Code": "eudeu",
    "Country": "Germany",
    "Religion is important": 219,
    "Religion is not important": 845,
    "Believe in God": 276,
    "Doesnt believe in God": 692,
    "Believe in Hell": 51,
    "Doesnt believe in Hell": 929,
    "Children with religious faith": 65,
    "Children without religious faith": 944
  },
  {
    "Year": 1999,
    "Code": "ashkg",
    "Country": "Hong Kong",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "asind",
    "Country": "India",
    "Religion is important": 984,
    "Religion is not important": 142,
    "Believe in God": "1,908",
    "Doesnt believe in God": 112,
    "Believe in Hell": 992,
    "Doesnt believe in Hell": 807,
    "Children with religious faith": 735,
    "Children without religious faith": "1,305"
  },
  {
    "Year": 1999,
    "Code": "asjor",
    "Country": "Jordan",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "askor",
    "Country": "South Korea",
    "Religion is important": 247,
    "Religion is not important": 196,
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": 207,
    "Children without religious faith": "1,042"
  },
  {
    "Year": 1999,
    "Code": "aslbn",
    "Country": "Lebanon",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "amys",
    "Country": "Malaysia",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "namex",
    "Country": "Mexico",
    "Religion is important": 686,
    "Religion is not important": 45,
    "Believe in God": "1,405",
    "Doesnt believe in God": 80,
    "Believe in Hell": 802,
    "Doesnt believe in Hell": 572,
    "Children with religious faith": 658,
    "Children without religious faith": 852
  },
  {
    "Year": 1999,
    "Code": "eunld",
    "Country": "Netherlands",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "afnga",
    "Country": "Nigeria",
    "Religion is important": "1,826",
    "Religion is not important": 5,
    "Believe in God": "1,980",
    "Doesnt believe in God": 15,
    "Believe in Hell": "1,705",
    "Doesnt believe in Hell": 238,
    "Children with religious faith": "1,438",
    "Children without religious faith": 558
  },
  {
    "Year": 1999,
    "Code": "aspak",
    "Country": "Pakistan",
    "Religion is important": 590,
    "Religion is not important": 1,
    "Believe in God": 733,
    "Doesnt believe in God": "-",
    "Believe in Hell": 733,
    "Doesnt believe in Hell": "-",
    "Children with religious faith": 590,
    "Children without religious faith": 142
  },
  {
    "Year": 1999,
    "Code": "saper",
    "Country": "Peru",
    "Religion is important": 645,
    "Religion is not important": 27,
    "Believe in God": "1,172",
    "Doesnt believe in God": 24,
    "Believe in Hell": 713,
    "Doesnt believe in Hell": 404,
    "Children with religious faith": 625,
    "Children without religious faith": 586
  },
  {
    "Year": 1999,
    "Code": "asphl",
    "Country": "Philippines",
    "Religion is important": 940,
    "Religion is not important": 3,
    "Believe in God": "1,195",
    "Doesnt believe in God": 3,
    "Believe in Hell": "1,055",
    "Doesnt believe in Hell": 99,
    "Children with religious faith": 752,
    "Children without religious faith": 448
  },
  {
    "Year": 1999,
    "Code": "eupol",
    "Country": "Poland",
    "Religion is important": 535,
    "Religion is not important": 37,
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "asqat",
    "Country": "Qatar",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "assgp",
    "Country": "Singapore",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "afzaf",
    "Country": "South Africa",
    "Religion is important": "1,991",
    "Religion is not important": 73,
    "Believe in God": "2,882",
    "Doesnt believe in God": 31,
    "Believe in Hell": "1,714",
    "Doesnt believe in Hell": 978,
    "Children with religious faith": "1,794",
    "Children without religious faith": "1,141"
  },
  {
    "Year": 1999,
    "Code": "afzwe",
    "Country": "Zimbabwe",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "euesp",
    "Country": "Spain",
    "Religion is important": 305,
    "Religion is not important": 168,
    "Believe in God": "1,053",
    "Doesnt believe in God": 105,
    "Believe in Hell": 388,
    "Doesnt believe in Hell": 653,
    "Children with religious faith": 263,
    "Children without religious faith": 947
  },
  {
    "Year": 1999,
    "Code": "euswe",
    "Country": "Sweden",
    "Religion is important": 96,
    "Religion is not important": 274,
    "Believe in God": 486,
    "Doesnt believe in God": 380,
    "Believe in Hell": 110,
    "Doesnt believe in Hell": 796,
    "Children with religious faith": 48,
    "Children without religious faith": 961
  },
  {
    "Year": 1999,
    "Code": "astur",
    "Country": "Turkey",
    "Religion is important": "1,590",
    "Religion is not important": 45,
    "Believe in God": "1,578",
    "Doesnt believe in God": 33,
    "Believe in Hell": "1,451",
    "Doesnt believe in Hell": 134,
    "Children with religious faith": 970,
    "Children without religious faith": 937
  },
  {
    "Year": 1999,
    "Code": "euukr",
    "Country": "Ukraine",
    "Religion is important": 537,
    "Religion is not important": 507,
    "Believe in God": "1,819",
    "Doesnt believe in God": 558,
    "Believe in Hell": 752,
    "Doesnt believe in Hell": "1,072",
    "Children with religious faith": 574,
    "Children without religious faith": "2,237"
  },
  {
    "Year": 1999,
    "Code": "afegy",
    "Country": "Egypt",
    "Religion is important": "",
    "Religion is not important": "",
    "Believe in God": "",
    "Doesnt believe in God": "",
    "Believe in Hell": "",
    "Doesnt believe in Hell": "",
    "Children with religious faith": "",
    "Children without religious faith": ""
  },
  {
    "Year": 1999,
    "Code": "nausa",
    "Country": "United States",
    "Religion is important": 861,
    "Religion is not important": 80,
    "Believe in God": "1,447",
    "Doesnt believe in God": 60,
    "Believe in Hell": "1,081",
    "Doesnt believe in Hell": 356,
    "Children with religious faith": 832,
    "Children without religious faith": 710
  }
]
